language: java
sudo: true
dist: trusty

# use Java 8
jdk: openjdk8

script: ./mvnw -DskipTests=true clean install

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: Install
      script: ./mvnw clean install sonar:sonar

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr