language: java
dist: trusty

# use Java 8
jdk: openjdk8

script:
  - ./mvnw clean install
  
before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr
