language: java
dist: trusty

# use Java 8
jdk: openjdk8

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: test
      script: ./mvnw clean test
    - stage: Install
      script: ./mvnw clean install
    - stage: SonarCloud
      script: ./mvnw verify sonar:sonar
    - stage: Cobertura
      script: ./mvnw cobertura:cobertura

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr
