language: java
sudo: true
dist: trusty

# use Java 8
jdk: openjdk8

before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: test
      script: ./mvnw clean test
    - stage: Install
      script: ./mvnw clean install
    - stage: SonarCloud
      script: ./mvnw sonar:sonar

cache:
  directories:
    - $HOME/.m2

notifications:
  email: pe.dsf@free.fr