version: "3.7"

services:
  myerp.db:
    image: postgres:alpine
    container_name: myerp_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db_myerp
      - POSTGRES_USER=usr_myerp
      - POSTGRES_PASSWORD=myerp
    volumes:
#     - "./data/db:/var/lib/postgresql/data"
      - "./docker/dev/init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      #- "127.0.0.1:9032:5432"
      - "9032:5432"
    networks:
      net:
        ipv4_address: 10.5.0.2
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - "myerp.db"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - "./docker/dev/pgadmin:/var/lib/pgadmin"
    ports:
      - "5050:80"
    networks:
      net:
        ipv4_address: 10.5.0.3


  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    restart: unless-stopped
    volumes:
      - ./docker/dev/jenkins:/var/jenkins_home
      - ./src:/var/jenkins_home/workspace/Myerp
    ports:
      - "5000:8080"
      - "443:8443"
      - "50000:50000"
    networks:
      net:
        ipv4_address: 10.5.0.4
    

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
    myerp.db:
    pgadmin:
    jenkins: